# -*- coding: utf-8 -*-
"""Exercício - 3 - List.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v-WEkwX83rTkMsZuaTg8XhzoxlirPHB9

**Exercício - 3 - List**
"""

Nome = ["Igor, Riam, Leao, Vitor, Enrico, Fabricio, Matheus, Jonas, Joao Lucas, Pedro"]

print(Nome)
['Igor, Riam, Leao, Vitor, Enrico, Fabricio, Matheus, Jonas, Joao Lucas, Pedro']



