# -*- coding: utf-8 -*-
"""Exercício - 4 - Dict - Itens da Geladeira.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T1vRU47r5IhLFHEusJZQNT5iXwK9lD66
"""



"""**Exercício - 4 - Dict - Itens da Geladeira**"""

ItensGeladeira= {
    "agua": "3",
    "ovos": "8",
    "quejoEmFatia": "6",
    "leite": "2",
    "alface": "3",
    "tomate": "4",
    "presuntoFatia": "4",
    "manteiga": "2",
    "requeijao": "1",
    "azeitona": "0deio"
}

print(ItensGeladeira)
{'agua': '3', 'ovos': '8', 'quejoEmFatia': '6', 'leite': '2', 'alface': '3', 'tomate': '4', 'presuntoFatia': '4', 'manteiga': '2', 'requeijao': '1', 'azeitona': '0deio'}