# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sj2RI-5E6DsBmEcGpWureQ7r-wyc9ty7
"""

ListaCompra= {"arroz", "feijao", "macarrao", "tomate", "batata", "açucar", "sal", "polvilhodoce", "leite", "milharina"}
print(ListaCompra)

