# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19reUhiWs3GZCGLFu8SRv6WwWkt7BChhW

**Exercício - 6 - Tupla - Lista de Siglas de Estados Brasileiros**
"""

Estados = ("PE", "AL", "SE", "BA", "MT", "DF", "GO", "MS", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "RR", "AP", "AM", "PA", "AC", "RO", "TO", "MA", "PI", "CE", "RN", "PB")
print(Estados)