# -*- coding: utf-8 -*-
"""Exercício 8 - Lista com vários tipos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B9nsic9xq9U8DQdp4lJMWMZy2jugEYZe

**Exercício 8 - Lista com vários tipos**
"""

Refrigerantes = ["coca", "guarana", "fanta", "pepsi"]
print(Refrigerantes[2])