# -*- coding: utf-8 -*-
"""Exercício 9 - Lista valor de item em posição por índice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9fEPK8rEKCkLSxwdK4zU-5zFaP9xRko

**Exercício 9 - Lista valor de item em posição por índice**
"""

Refrigerantes = ["coca", "guarana", "fanta", "pepsi", "bare"]
Sucos = ["uva", "laranja", "maracuja", "abacaxi", "acerola"]
Refeicao = ["galinhada", "feijoada", "estrogonofe", "salada", "lasanha"]

print(Refrigerantes[3])

Refrigerantes[3] = "abacaxi"
print(Refrigerantes[3])