# -*- coding: utf-8 -*-
"""Exercício 10 - Lista dentro de lista.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y2FKFlo7D5oQ3QHQQvNNmpjgqWoT9oAh

**Exercício 10 - Lista dentro de lista**
"""

Refrigerantes = ["coca", "guarana", "bare"]
Refeicao = ["galinhada", "feijoada", "estrogonofe"]

Refrigerantes.extend(Refeicao)
print(Refrigerantes)