# -*- coding: utf-8 -*-
"""Exercício 11 - Dict dentro de lista e remoção de item por índice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BK7HaozQPbHUEmMeSYVXg_cSzJmmrqMT

**Exercício 11 - Dict dentro de lista e remoção de item por índice**
"""

lista = ['henrique,' 'joana', 'vitor']
dicionario = {
    'pedro': 'professor',
    'marcos': 'aluno',
    'severino': 'assistente',
    'marta': 'técnico'
}
print(lista)
lista.append(dicionario)
print(lista)
del(lista[0])
print(lista)