# -*- coding: utf-8 -*-
"""Exercício - 12 - Function - Criar função.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S2IA_Fl8YQlIiQjakBII0iqtjF4wmc-Y

***Exercício - 12 - Function - Criar função***
"""

def primeira_funcao(nome, idade):
    print(f"Nome:{nome}\nIdade:{idade}")

primeira_funcao("Hézio", "18 anos")

