# -*- coding: utf-8 -*-
"""Exercício - 13 - Function - Lista adicionar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uRb5arAYwCqZjXr3zLxk4EXW9UC_IB5d

**Exercício - 13 - Function - Lista adicionar**
"""

lista = [3, 6, 9]
lista_2 = [6, 12, 18]

def aumenta_lista(lista_original, lista_adicional):
    for cont in range(len(lista_adicional)):
        lista_original.append(lista_adicional[cont])

print(f"Lista antes da adição de novos itens: {lista}")

aumenta_lista(lista, lista_2)

print(f"Lista depois da adição de novos itens: {lista}")