# -*- coding: utf-8 -*-
"""Exercício - 14 - Function - Lista alterar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xuU8ONIKGRvpXG35GQttIOO3IaW_V_6l

**Exercício - 14 - Function - Lista alterar**
"""

lista = [6, 4, 2]


def altera(lista_modelo):
    lista_modelo[1] = 3


print(f"Lista antes da alteração:{lista}")

altera(lista)

print(f"Lista depois da alteração:{lista}")