# -*- coding: utf-8 -*-
"""Exercício - 15 - Function - Lista ordenar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ynLX0LYKDpPYIVC2urvuTXSDj_xNL_Bm

**Exercício - 15 - Function - Lista ordenar**
"""

lista = [3, 6, 21, 1, 5, 98, 4, 23, 1, 6]


def ordena(lista_modelo):
    lista_modelo.sort()


print(f"Lista antes da alteração:{lista}")

ordena(lista)

print(f"Lista depois da alteração:{lista}")