# -*- coding: utf-8 -*-
"""Exercício - 16 - Function - Lista ordenada invertida.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13G-exebcBOkgWAYF8VDJeZGczb86u3wu

**Exercício - 16 - Function - Lista ordenada invertida**
"""

lista = [3, 6, 21, 1, 5, 98, 4, 23, 1, 6]


def reverte(lista_modelo):
    lista_modelo.sort()
    lista_modelo.reverse()


print(f"Lista antes da alteração:{lista}")

reverte(lista)

print(f"Lista depois da alteração:{lista}")

# Referencias:
# https://pynative.com/python-range-function