# -*- coding: utf-8 -*-
"""Exercício - 17 - Function - Lista de Alunos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12rZgOIPHiG_q3kM2CT6r16qkXViY3_Cl

**Exercício - 17 - Function - Lista de Alunos**
"""

lista_alunos = [
    "Welson",
    "Ryam",
    "Welisson",
    "Webson",
    "Pedro",
    "Joao",
    "Maria",
    "Isadora",
    "Vini",
    "Sayuri"
]


def listagem(lista_modelo):
    for cont in range(len(lista_modelo)):
        print(f"Nome do Aluno: {lista_modelo[cont]}")


listagem(lista_alunos)